//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransferAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_period
    {
        public System.Guid guid { get; set; }
        public System.Guid employee_guid { get; set; }
        public System.DateTime begin_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
